services:
  - type: web
    name: gplink-to-arolink-bot
    runtime: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: GPLINKS_API_KEY
        value: YOUR_GPLINKS_API_KEY
      - key: AROLINKS_API_KEY
        value: YOUR_AROLINKS_API_KEY
    build:
      environment:
        PYTHON_VERSION: 3.10.12
